jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm run test

name: Test

on:
  pull_request: ~
  push:
    branches:
      - main
