jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm run test

      - name: Test local action
        id: test-action
        uses: ./
        with:
          url: https://johnnyreilly.com

name: Test

on:
  pull_request: ~
  push:
    branches:
      - main
